/**
 * Seed data for multiple cities
 * 20+ real budget restaurants per city with realistic data
 * All data based on publicly known restaurant/chain information
 */

import type { RestaurantListItem } from '@valuebite/types';

// Unsplash placeholder images for food categories
const PHOTOS = {
  burger: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop',
  pizza: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=300&fit=crop',
  deli: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=400&h=300&fit=crop',
  mexican: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&h=300&fit=crop',
  chinese: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400&h=300&fit=crop',
  indian: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop',
  thai: 'https://images.unsplash.com/photo-1562565652-a0d8f0c59eb4?w=400&h=300&fit=crop',
  vietnamese: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=400&h=300&fit=crop',
  mediterranean: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=300&fit=crop',
  british: 'https://images.unsplash.com/photo-1432139509613-5c4255a1d197?w=400&h=300&fit=crop',
  french: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=300&fit=crop',
  hawker: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&h=300&fit=crop',
  kebab: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400&h=300&fit=crop',
  salad: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop',
  coffee: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=300&fit=crop',
  ramen: 'https://images.unsplash.com/photo-1557872943-16a5ac26437e?w=400&h=300&fit=crop',
  sushi: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400&h=300&fit=crop',
};

// Restaurant data organized by city
export const CITY_RESTAURANTS: Record<string, RestaurantListItem[]> = {

  // =====================================================================
  // NEW YORK CITY
  // =====================================================================
  nyc: [
    // --- Pizza ---
    { id: 'nyc-1', name: { original: "Joe's Pizza", en: "Joe's Pizza", romanized: "Joe's Pizza" }, slug: 'joes-pizza-greenwich', cuisineType: ['pizza', 'italian'], lat: 40.7306, lng: -74.0021, avgMealPrice: 3.50, priceCurrency: 'USD', valueScore: 4.8, tasteScore: 4.5, portionScore: 4.0, totalReviews: 1245, photoUrl: PHOTOS.pizza, distance: 200, purposeFit: 0.95, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'nyc-2', name: { original: '2 Bros Pizza', en: '2 Bros Pizza', romanized: '2 Bros Pizza' }, slug: '2-bros-pizza-midtown', cuisineType: ['pizza', 'italian'], lat: 40.7536, lng: -73.9870, avgMealPrice: 1.50, priceCurrency: 'USD', valueScore: 4.9, tasteScore: 3.5, portionScore: 4.0, totalReviews: 876, photoUrl: PHOTOS.pizza, distance: 350, purposeFit: 0.98, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'nyc-3', name: { original: 'Prince St Pizza', en: 'Prince St Pizza', romanized: 'Prince St Pizza' }, slug: 'prince-st-pizza-nolita', cuisineType: ['pizza', 'italian'], lat: 40.7234, lng: -73.9946, avgMealPrice: 5.00, priceCurrency: 'USD', valueScore: 4.4, tasteScore: 4.7, portionScore: 4.2, totalReviews: 967, photoUrl: PHOTOS.pizza, distance: 280, purposeFit: 0.88, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Fast Casual Chains ---
    { id: 'nyc-4', name: { original: 'Chipotle', en: 'Chipotle Mexican Grill', romanized: 'Chipotle' }, slug: 'chipotle-union-sq', cuisineType: ['mexican', 'fast-casual'], lat: 40.7359, lng: -73.9911, avgMealPrice: 11.00, priceCurrency: 'USD', valueScore: 3.9, tasteScore: 3.8, portionScore: 4.5, totalReviews: 534, photoUrl: PHOTOS.mexican, distance: 400, purposeFit: 0.82, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'nyc-5', name: { original: 'Shake Shack', en: 'Shake Shack Madison Square Park', romanized: 'Shake Shack' }, slug: 'shake-shack-madison-sq', cuisineType: ['burger', 'american'], lat: 40.7415, lng: -73.9880, avgMealPrice: 12.00, priceCurrency: 'USD', valueScore: 3.7, tasteScore: 4.3, portionScore: 3.5, totalReviews: 1567, photoUrl: PHOTOS.burger, distance: 500, purposeFit: 0.75, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'nyc-6', name: { original: 'Sweetgreen', en: 'Sweetgreen', romanized: 'Sweetgreen' }, slug: 'sweetgreen-nomad', cuisineType: ['salad', 'healthy'], lat: 40.7450, lng: -73.9875, avgMealPrice: 14.00, priceCurrency: 'USD', valueScore: 3.5, tasteScore: 4.0, portionScore: 3.3, totalReviews: 312, photoUrl: PHOTOS.salad, distance: 450, purposeFit: 0.70, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'nyc-7', name: { original: 'Chick-fil-A', en: 'Chick-fil-A Fulton St', romanized: 'Chick-fil-A' }, slug: 'chick-fil-a-fulton', cuisineType: ['chicken', 'fast-food'], lat: 40.7095, lng: -74.0064, avgMealPrice: 9.00, priceCurrency: 'USD', valueScore: 4.1, tasteScore: 4.2, portionScore: 3.8, totalReviews: 789, photoUrl: PHOTOS.burger, distance: 600, purposeFit: 0.85, isChain: true, freshnessIndicator: { label: 'Verified 1-3 months ago', color: 'yellow', icon: 'clock' } },

    // --- Chinese ---
    { id: 'nyc-8', name: { original: "Xi'an Famous Foods", en: "Xi'an Famous Foods", romanized: "Xi'an Famous Foods" }, slug: 'xian-famous-foods-midtown', cuisineType: ['chinese', 'noodles'], lat: 40.7567, lng: -73.9854, avgMealPrice: 9.50, priceCurrency: 'USD', valueScore: 4.5, tasteScore: 4.6, portionScore: 4.2, totalReviews: 1023, photoUrl: PHOTOS.chinese, distance: 320, purposeFit: 0.90, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'nyc-9', name: { original: 'Wonton Noodle', en: 'Wonton Noodle', romanized: 'Wonton Noodle' }, slug: 'wonton-noodle-chinatown', cuisineType: ['chinese', 'noodles'], lat: 40.7157, lng: -73.9977, avgMealPrice: 7.00, priceCurrency: 'USD', valueScore: 4.6, tasteScore: 4.3, portionScore: 4.0, totalReviews: 567, photoUrl: PHOTOS.chinese, distance: 250, purposeFit: 0.92, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'nyc-10', name: { original: "Joe's Shanghai", en: "Joe's Shanghai", romanized: "Joe's Shanghai" }, slug: 'joes-shanghai-chinatown', cuisineType: ['chinese', 'shanghainese'], lat: 40.7155, lng: -73.9984, avgMealPrice: 12.00, priceCurrency: 'USD', valueScore: 4.2, tasteScore: 4.5, portionScore: 4.3, totalReviews: 834, photoUrl: PHOTOS.chinese, distance: 260, purposeFit: 0.82, isChain: false, freshnessIndicator: { label: 'Verified 1-3 months ago', color: 'yellow', icon: 'clock' } },

    // --- Halal Carts ---
    { id: 'nyc-11', name: { original: 'The Halal Guys', en: 'The Halal Guys', romanized: 'The Halal Guys' }, slug: 'halal-guys-midtown', cuisineType: ['halal', 'middle-eastern'], lat: 40.7618, lng: -73.9798, avgMealPrice: 8.00, priceCurrency: 'USD', valueScore: 4.6, tasteScore: 4.4, portionScore: 4.8, totalReviews: 2134, photoUrl: PHOTOS.kebab, distance: 380, purposeFit: 0.92, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'nyc-12', name: { original: "Rafiqi's Halal Food", en: "Rafiqi's Halal Food", romanized: "Rafiqi's" }, slug: 'rafiqis-halal-midtown', cuisineType: ['halal', 'middle-eastern'], lat: 40.7510, lng: -73.9825, avgMealPrice: 7.00, priceCurrency: 'USD', valueScore: 4.5, tasteScore: 4.0, portionScore: 4.6, totalReviews: 456, photoUrl: PHOTOS.kebab, distance: 420, purposeFit: 0.90, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Delis ---
    { id: 'nyc-13', name: { original: "Katz's Delicatessen", en: "Katz's Delicatessen", romanized: "Katz's Deli" }, slug: 'katzs-deli-les', cuisineType: ['deli', 'american'], lat: 40.7223, lng: -73.9874, avgMealPrice: 15.00, priceCurrency: 'USD', valueScore: 3.8, tasteScore: 4.8, portionScore: 4.7, totalReviews: 3456, photoUrl: PHOTOS.deli, distance: 310, purposeFit: 0.72, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'nyc-14', name: { original: 'Russ & Daughters Cafe', en: 'Russ & Daughters Cafe', romanized: 'Russ & Daughters' }, slug: 'russ-daughters-les', cuisineType: ['deli', 'jewish'], lat: 40.7221, lng: -73.9883, avgMealPrice: 14.00, priceCurrency: 'USD', valueScore: 3.9, tasteScore: 4.7, portionScore: 3.8, totalReviews: 1234, photoUrl: PHOTOS.deli, distance: 320, purposeFit: 0.70, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Bagels ---
    { id: 'nyc-15', name: { original: 'Absolute Bagels', en: 'Absolute Bagels', romanized: 'Absolute Bagels' }, slug: 'absolute-bagels-uws', cuisineType: ['bagel', 'bakery'], lat: 40.8028, lng: -73.9662, avgMealPrice: 4.50, priceCurrency: 'USD', valueScore: 4.7, tasteScore: 4.6, portionScore: 4.0, totalReviews: 789, photoUrl: PHOTOS.deli, distance: 1200, purposeFit: 0.90, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'nyc-16', name: { original: 'Ess-a-Bagel', en: 'Ess-a-Bagel', romanized: 'Ess-a-Bagel' }, slug: 'ess-a-bagel-midtown', cuisineType: ['bagel', 'bakery'], lat: 40.7568, lng: -73.9703, avgMealPrice: 5.00, priceCurrency: 'USD', valueScore: 4.5, tasteScore: 4.5, portionScore: 4.3, totalReviews: 654, photoUrl: PHOTOS.deli, distance: 380, purposeFit: 0.88, isChain: false, freshnessIndicator: { label: 'Verified 1-3 months ago', color: 'yellow', icon: 'clock' } },

    // --- Mexican ---
    { id: 'nyc-17', name: { original: 'Los Tacos No.1', en: 'Los Tacos No.1', romanized: 'Los Tacos No.1' }, slug: 'los-tacos-chelsea-market', cuisineType: ['mexican', 'tacos'], lat: 40.7425, lng: -74.0060, avgMealPrice: 8.00, priceCurrency: 'USD', valueScore: 4.6, tasteScore: 4.7, portionScore: 3.9, totalReviews: 1456, photoUrl: PHOTOS.mexican, distance: 550, purposeFit: 0.88, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'nyc-18', name: { original: 'Taco Bell', en: 'Taco Bell', romanized: 'Taco Bell' }, slug: 'taco-bell-union-sq', cuisineType: ['mexican', 'fast-food'], lat: 40.7340, lng: -73.9905, avgMealPrice: 6.00, priceCurrency: 'USD', valueScore: 4.0, tasteScore: 3.2, portionScore: 3.8, totalReviews: 345, photoUrl: PHOTOS.mexican, distance: 410, purposeFit: 0.85, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Thai / Vietnamese / Indian ---
    { id: 'nyc-19', name: { original: 'Thai Son', en: 'Thai Son Vietnamese', romanized: 'Thai Son' }, slug: 'thai-son-chinatown', cuisineType: ['vietnamese', 'pho'], lat: 40.7170, lng: -73.9990, avgMealPrice: 9.00, priceCurrency: 'USD', valueScore: 4.4, tasteScore: 4.3, portionScore: 4.2, totalReviews: 567, photoUrl: PHOTOS.vietnamese, distance: 270, purposeFit: 0.85, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'nyc-20', name: { original: 'Panna II Garden', en: 'Panna II Garden Indian', romanized: 'Panna II' }, slug: 'panna-ii-east-village', cuisineType: ['indian', 'curry'], lat: 40.7268, lng: -73.9845, avgMealPrice: 10.00, priceCurrency: 'USD', valueScore: 4.3, tasteScore: 4.1, portionScore: 4.4, totalReviews: 456, photoUrl: PHOTOS.indian, distance: 340, purposeFit: 0.80, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'nyc-21', name: { original: 'Pad Thai', en: 'Pad Thai', romanized: 'Pad Thai' }, slug: 'pad-thai-hells-kitchen', cuisineType: ['thai', 'noodles'], lat: 40.7623, lng: -73.9912, avgMealPrice: 8.50, priceCurrency: 'USD', valueScore: 4.4, tasteScore: 4.2, portionScore: 4.0, totalReviews: 312, photoUrl: PHOTOS.thai, distance: 390, purposeFit: 0.85, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Diners ---
    { id: 'nyc-22', name: { original: "Tom's Restaurant", en: "Tom's Restaurant", romanized: "Tom's Restaurant" }, slug: 'toms-restaurant-morningside', cuisineType: ['diner', 'american'], lat: 40.8057, lng: -73.9658, avgMealPrice: 10.00, priceCurrency: 'USD', valueScore: 3.9, tasteScore: 3.6, portionScore: 4.2, totalReviews: 987, photoUrl: PHOTOS.burger, distance: 1250, purposeFit: 0.78, isChain: false, freshnessIndicator: { label: 'Verified 1-3 months ago', color: 'yellow', icon: 'clock' } },
    { id: 'nyc-23', name: { original: 'Empire Diner', en: 'Empire Diner', romanized: 'Empire Diner' }, slug: 'empire-diner-chelsea', cuisineType: ['diner', 'american'], lat: 40.7463, lng: -74.0038, avgMealPrice: 13.00, priceCurrency: 'USD', valueScore: 3.6, tasteScore: 3.9, portionScore: 4.0, totalReviews: 567, photoUrl: PHOTOS.burger, distance: 520, purposeFit: 0.72, isChain: false, freshnessIndicator: { label: 'Verified 1-3 months ago', color: 'yellow', icon: 'clock' } },
  ],

  // =====================================================================
  // LONDON
  // =====================================================================
  london: [
    // --- Fish & Chips ---
    { id: 'ldn-1', name: { original: 'Poppies Fish & Chips', en: 'Poppies Fish & Chips', romanized: 'Poppies' }, slug: 'poppies-spitalfields', cuisineType: ['british', 'fish-and-chips'], lat: 51.5196, lng: -0.0756, avgMealPrice: 10.50, priceCurrency: 'GBP', valueScore: 4.2, tasteScore: 4.4, portionScore: 4.3, totalReviews: 1234, photoUrl: PHOTOS.british, distance: 300, purposeFit: 0.85, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'ldn-2', name: { original: 'The Golden Hind', en: 'The Golden Hind', romanized: 'The Golden Hind' }, slug: 'golden-hind-marylebone', cuisineType: ['british', 'fish-and-chips'], lat: 51.5182, lng: -0.1498, avgMealPrice: 11.00, priceCurrency: 'GBP', valueScore: 4.3, tasteScore: 4.5, portionScore: 4.2, totalReviews: 876, photoUrl: PHOTOS.british, distance: 450, purposeFit: 0.83, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Chains ---
    { id: 'ldn-3', name: { original: "Nando's", en: "Nando's Soho", romanized: "Nando's" }, slug: 'nandos-soho', cuisineType: ['chicken', 'portuguese'], lat: 51.5132, lng: -0.1325, avgMealPrice: 10.00, priceCurrency: 'GBP', valueScore: 4.0, tasteScore: 4.1, portionScore: 3.9, totalReviews: 789, photoUrl: PHOTOS.burger, distance: 200, purposeFit: 0.85, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'ldn-4', name: { original: 'Greggs', en: 'Greggs Baker', romanized: 'Greggs' }, slug: 'greggs-strand', cuisineType: ['bakery', 'british'], lat: 51.5112, lng: -0.1184, avgMealPrice: 3.50, priceCurrency: 'GBP', valueScore: 4.7, tasteScore: 3.5, portionScore: 3.8, totalReviews: 1456, photoUrl: PHOTOS.british, distance: 150, purposeFit: 0.95, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'ldn-5', name: { original: 'Wetherspoons', en: 'The Moon Under Water', romanized: 'Wetherspoons' }, slug: 'wetherspoons-leicester-sq', cuisineType: ['pub', 'british'], lat: 51.5106, lng: -0.1312, avgMealPrice: 7.50, priceCurrency: 'GBP', valueScore: 4.3, tasteScore: 3.3, portionScore: 4.5, totalReviews: 2345, photoUrl: PHOTOS.british, distance: 180, purposeFit: 0.88, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'ldn-6', name: { original: 'Pret A Manger', en: 'Pret A Manger', romanized: 'Pret A Manger' }, slug: 'pret-victoria', cuisineType: ['cafe', 'sandwich'], lat: 51.5000, lng: -0.1427, avgMealPrice: 6.00, priceCurrency: 'GBP', valueScore: 3.8, tasteScore: 3.7, portionScore: 3.3, totalReviews: 567, photoUrl: PHOTOS.coffee, distance: 350, purposeFit: 0.80, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Indian ---
    { id: 'ldn-7', name: { original: 'Dishoom', en: 'Dishoom Covent Garden', romanized: 'Dishoom' }, slug: 'dishoom-covent-garden', cuisineType: ['indian', 'bombay-cafe'], lat: 51.5124, lng: -0.1247, avgMealPrice: 12.00, priceCurrency: 'GBP', valueScore: 4.1, tasteScore: 4.6, portionScore: 4.0, totalReviews: 3456, photoUrl: PHOTOS.indian, distance: 250, purposeFit: 0.78, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'ldn-8', name: { original: 'Tayyabs', en: 'Tayyabs', romanized: 'Tayyabs' }, slug: 'tayyabs-whitechapel', cuisineType: ['indian', 'pakistani'], lat: 51.5162, lng: -0.0656, avgMealPrice: 8.00, priceCurrency: 'GBP', valueScore: 4.6, tasteScore: 4.5, portionScore: 4.4, totalReviews: 2345, photoUrl: PHOTOS.indian, distance: 500, purposeFit: 0.90, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'ldn-9', name: { original: 'Lahore Kebab House', en: 'Lahore Kebab House', romanized: 'Lahore Kebab House' }, slug: 'lahore-kebab-whitechapel', cuisineType: ['pakistani', 'kebab'], lat: 51.5155, lng: -0.0665, avgMealPrice: 7.50, priceCurrency: 'GBP', valueScore: 4.7, tasteScore: 4.4, portionScore: 4.6, totalReviews: 1789, photoUrl: PHOTOS.kebab, distance: 510, purposeFit: 0.92, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Kebab ---
    { id: 'ldn-10', name: { original: 'Mangal 1', en: 'Mangal 1 Ocakbasi', romanized: 'Mangal 1' }, slug: 'mangal-1-dalston', cuisineType: ['turkish', 'kebab'], lat: 51.5465, lng: -0.0752, avgMealPrice: 9.00, priceCurrency: 'GBP', valueScore: 4.5, tasteScore: 4.6, portionScore: 4.3, totalReviews: 987, photoUrl: PHOTOS.kebab, distance: 800, purposeFit: 0.85, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'ldn-11', name: { original: 'Best Mangal', en: 'Best Mangal', romanized: 'Best Mangal' }, slug: 'best-mangal-fulham', cuisineType: ['turkish', 'kebab'], lat: 51.4826, lng: -0.1962, avgMealPrice: 8.50, priceCurrency: 'GBP', valueScore: 4.4, tasteScore: 4.3, portionScore: 4.5, totalReviews: 678, photoUrl: PHOTOS.kebab, distance: 900, purposeFit: 0.87, isChain: false, freshnessIndicator: { label: 'Verified 1-3 months ago', color: 'yellow', icon: 'clock' } },

    // --- Chinese / Vietnamese in Chinatown ---
    { id: 'ldn-12', name: { original: 'Wong Kei', en: 'Wong Kei', romanized: 'Wong Kei' }, slug: 'wong-kei-chinatown', cuisineType: ['chinese', 'cantonese'], lat: 51.5118, lng: -0.1310, avgMealPrice: 8.00, priceCurrency: 'GBP', valueScore: 4.4, tasteScore: 3.9, portionScore: 4.5, totalReviews: 1567, photoUrl: PHOTOS.chinese, distance: 190, purposeFit: 0.88, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'ldn-13', name: { original: 'Baozi Inn', en: 'Baozi Inn', romanized: 'Baozi Inn' }, slug: 'baozi-inn-chinatown', cuisineType: ['chinese', 'street-food'], lat: 51.5113, lng: -0.1305, avgMealPrice: 7.00, priceCurrency: 'GBP', valueScore: 4.5, tasteScore: 4.2, portionScore: 3.9, totalReviews: 876, photoUrl: PHOTOS.chinese, distance: 195, purposeFit: 0.90, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'ldn-14', name: { original: 'Pho', en: 'Pho Vietnamese', romanized: 'Pho' }, slug: 'pho-soho', cuisineType: ['vietnamese', 'pho'], lat: 51.5135, lng: -0.1340, avgMealPrice: 9.50, priceCurrency: 'GBP', valueScore: 4.1, tasteScore: 4.2, portionScore: 4.0, totalReviews: 654, photoUrl: PHOTOS.vietnamese, distance: 220, purposeFit: 0.82, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Market Food ---
    { id: 'ldn-15', name: { original: 'Borough Market Stall', en: 'Borough Market Grilled Cheese', romanized: 'Borough Market' }, slug: 'borough-market-stall', cuisineType: ['market', 'street-food'], lat: 51.5055, lng: -0.0910, avgMealPrice: 6.50, priceCurrency: 'GBP', valueScore: 4.3, tasteScore: 4.4, portionScore: 3.5, totalReviews: 345, photoUrl: PHOTOS.british, distance: 350, purposeFit: 0.82, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'ldn-16', name: { original: 'Padella', en: 'Padella', romanized: 'Padella' }, slug: 'padella-borough', cuisineType: ['italian', 'pasta'], lat: 51.5053, lng: -0.0915, avgMealPrice: 8.00, priceCurrency: 'GBP', valueScore: 4.6, tasteScore: 4.7, portionScore: 3.8, totalReviews: 2345, photoUrl: PHOTOS.pizza, distance: 355, purposeFit: 0.85, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- More budget spots ---
    { id: 'ldn-17', name: { original: 'Bao', en: 'Bao Soho', romanized: 'Bao' }, slug: 'bao-soho', cuisineType: ['taiwanese', 'bao'], lat: 51.5130, lng: -0.1345, avgMealPrice: 7.00, priceCurrency: 'GBP', valueScore: 4.4, tasteScore: 4.5, portionScore: 3.5, totalReviews: 1234, photoUrl: PHOTOS.hawker, distance: 210, purposeFit: 0.82, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'ldn-18', name: { original: 'Flat Iron', en: 'Flat Iron Steak', romanized: 'Flat Iron' }, slug: 'flat-iron-soho', cuisineType: ['steak', 'british'], lat: 51.5140, lng: -0.1355, avgMealPrice: 11.00, priceCurrency: 'GBP', valueScore: 4.5, tasteScore: 4.5, portionScore: 4.0, totalReviews: 1567, photoUrl: PHOTOS.british, distance: 215, purposeFit: 0.80, isChain: true, freshnessIndicator: { label: 'Verified 1-3 months ago', color: 'yellow', icon: 'clock' } },
    { id: 'ldn-19', name: { original: 'Franco Manca', en: 'Franco Manca', romanized: 'Franco Manca' }, slug: 'franco-manca-brixton', cuisineType: ['pizza', 'italian'], lat: 51.5095, lng: -0.1265, avgMealPrice: 7.50, priceCurrency: 'GBP', valueScore: 4.6, tasteScore: 4.4, portionScore: 4.0, totalReviews: 987, photoUrl: PHOTOS.pizza, distance: 280, purposeFit: 0.88, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'ldn-20', name: { original: 'Honest Burgers', en: 'Honest Burgers', romanized: 'Honest Burgers' }, slug: 'honest-burgers-brixton', cuisineType: ['burger', 'british'], lat: 51.5098, lng: -0.1272, avgMealPrice: 11.50, priceCurrency: 'GBP', valueScore: 4.0, tasteScore: 4.3, portionScore: 4.1, totalReviews: 876, photoUrl: PHOTOS.burger, distance: 290, purposeFit: 0.78, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'ldn-21', name: { original: 'Morleys', en: 'Morleys Fried Chicken', romanized: 'Morleys' }, slug: 'morleys-peckham', cuisineType: ['chicken', 'fast-food'], lat: 51.5148, lng: -0.0692, avgMealPrice: 4.50, priceCurrency: 'GBP', valueScore: 4.5, tasteScore: 3.6, portionScore: 4.4, totalReviews: 567, photoUrl: PHOTOS.burger, distance: 600, purposeFit: 0.90, isChain: true, freshnessIndicator: { label: 'Verified 1-3 months ago', color: 'yellow', icon: 'clock' } },
  ],

  // =====================================================================
  // PARIS
  // =====================================================================
  paris: [
    // --- Boulangeries / Sandwich ---
    { id: 'par-1', name: { original: 'Boulangerie Maison Kayser', en: 'Maison Kayser Bakery', romanized: 'Maison Kayser' }, slug: 'maison-kayser-marais', cuisineType: ['french', 'bakery'], lat: 48.8566, lng: 2.3522, avgMealPrice: 5.50, priceCurrency: 'EUR', valueScore: 4.3, tasteScore: 4.5, portionScore: 3.5, totalReviews: 987, photoUrl: PHOTOS.french, distance: 200, purposeFit: 0.88, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'par-2', name: { original: 'Eric Kayser', en: 'Eric Kayser Bakery', romanized: 'Eric Kayser' }, slug: 'eric-kayser-odeon', cuisineType: ['french', 'bakery'], lat: 48.8512, lng: 2.3387, avgMealPrice: 6.00, priceCurrency: 'EUR', valueScore: 4.2, tasteScore: 4.6, portionScore: 3.4, totalReviews: 765, photoUrl: PHOTOS.french, distance: 350, purposeFit: 0.85, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'par-3', name: { original: 'Paul', en: 'Paul Bakery', romanized: 'Paul' }, slug: 'paul-chatelet', cuisineType: ['french', 'bakery', 'sandwich'], lat: 48.8580, lng: 2.3470, avgMealPrice: 5.00, priceCurrency: 'EUR', valueScore: 4.0, tasteScore: 3.8, portionScore: 3.5, totalReviews: 1234, photoUrl: PHOTOS.french, distance: 150, purposeFit: 0.90, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Creperies ---
    { id: 'par-4', name: { original: 'Breizh Cafe', en: 'Breizh Cafe', romanized: 'Breizh Cafe' }, slug: 'breizh-cafe-marais', cuisineType: ['french', 'crepe'], lat: 48.8612, lng: 2.3585, avgMealPrice: 8.50, priceCurrency: 'EUR', valueScore: 4.1, tasteScore: 4.5, portionScore: 3.8, totalReviews: 1567, photoUrl: PHOTOS.french, distance: 280, purposeFit: 0.82, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'par-5', name: { original: 'La Creperie de Josselin', en: 'Creperie de Josselin', romanized: 'Creperie de Josselin' }, slug: 'creperie-josselin-montparnasse', cuisineType: ['french', 'crepe'], lat: 48.8424, lng: 2.3265, avgMealPrice: 7.00, priceCurrency: 'EUR', valueScore: 4.4, tasteScore: 4.3, portionScore: 4.0, totalReviews: 876, photoUrl: PHOTOS.french, distance: 600, purposeFit: 0.85, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Kebab / Falafel ---
    { id: 'par-6', name: { original: "L'As du Fallafel", en: "L'As du Fallafel", romanized: "L'As du Fallafel" }, slug: 'las-du-fallafel-marais', cuisineType: ['middle-eastern', 'falafel'], lat: 48.8574, lng: 2.3590, avgMealPrice: 7.50, priceCurrency: 'EUR', valueScore: 4.7, tasteScore: 4.6, portionScore: 4.5, totalReviews: 3456, photoUrl: PHOTOS.kebab, distance: 250, purposeFit: 0.92, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'par-7', name: { original: 'Maison du Falafel', en: 'Maison du Falafel', romanized: 'Maison du Falafel' }, slug: 'maison-falafel-marais', cuisineType: ['middle-eastern', 'falafel'], lat: 48.8572, lng: 2.3588, avgMealPrice: 6.50, priceCurrency: 'EUR', valueScore: 4.5, tasteScore: 4.3, portionScore: 4.3, totalReviews: 1234, photoUrl: PHOTOS.kebab, distance: 255, purposeFit: 0.90, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'par-8', name: { original: 'Kebab de la Huchette', en: 'Kebab de la Huchette', romanized: 'Kebab de la Huchette' }, slug: 'kebab-huchette-latin-quarter', cuisineType: ['kebab', 'turkish'], lat: 48.8525, lng: 2.3467, avgMealPrice: 6.00, priceCurrency: 'EUR', valueScore: 4.3, tasteScore: 3.8, portionScore: 4.2, totalReviews: 567, photoUrl: PHOTOS.kebab, distance: 180, purposeFit: 0.88, isChain: false, freshnessIndicator: { label: 'Verified 1-3 months ago', color: 'yellow', icon: 'clock' } },

    // --- Vietnamese ---
    { id: 'par-9', name: { original: 'Pho 14', en: 'Pho 14', romanized: 'Pho 14' }, slug: 'pho-14-13eme', cuisineType: ['vietnamese', 'pho'], lat: 48.8282, lng: 2.3445, avgMealPrice: 8.00, priceCurrency: 'EUR', valueScore: 4.6, tasteScore: 4.4, portionScore: 4.3, totalReviews: 2345, photoUrl: PHOTOS.vietnamese, distance: 700, purposeFit: 0.90, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'par-10', name: { original: 'Pho Tai', en: 'Pho Tai', romanized: 'Pho Tai' }, slug: 'pho-tai-13eme', cuisineType: ['vietnamese', 'pho'], lat: 48.8278, lng: 2.3440, avgMealPrice: 7.50, priceCurrency: 'EUR', valueScore: 4.5, tasteScore: 4.3, portionScore: 4.2, totalReviews: 876, photoUrl: PHOTOS.vietnamese, distance: 710, purposeFit: 0.88, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'par-11', name: { original: 'Song Huong', en: 'Song Huong Vietnamese', romanized: 'Song Huong' }, slug: 'song-huong-13eme', cuisineType: ['vietnamese', 'banh-mi'], lat: 48.8275, lng: 2.3450, avgMealPrice: 6.50, priceCurrency: 'EUR', valueScore: 4.6, tasteScore: 4.2, portionScore: 4.4, totalReviews: 654, photoUrl: PHOTOS.vietnamese, distance: 720, purposeFit: 0.90, isChain: false, freshnessIndicator: { label: 'Verified 1-3 months ago', color: 'yellow', icon: 'clock' } },

    // --- Bistro Chains ---
    { id: 'par-12', name: { original: 'Hippopotamus', en: 'Hippopotamus Grill', romanized: 'Hippopotamus' }, slug: 'hippopotamus-bastille', cuisineType: ['french', 'grill'], lat: 48.8530, lng: 2.3690, avgMealPrice: 11.00, priceCurrency: 'EUR', valueScore: 3.7, tasteScore: 3.5, portionScore: 4.0, totalReviews: 345, photoUrl: PHOTOS.french, distance: 400, purposeFit: 0.75, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'par-13', name: { original: 'Buffalo Grill', en: 'Buffalo Grill', romanized: 'Buffalo Grill' }, slug: 'buffalo-grill-republique', cuisineType: ['american', 'grill'], lat: 48.8674, lng: 2.3640, avgMealPrice: 10.00, priceCurrency: 'EUR', valueScore: 3.8, tasteScore: 3.4, portionScore: 4.2, totalReviews: 234, photoUrl: PHOTOS.burger, distance: 350, purposeFit: 0.78, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Budget French Bistros ---
    { id: 'par-14', name: { original: 'Le Bouillon Chartier', en: 'Bouillon Chartier', romanized: 'Bouillon Chartier' }, slug: 'bouillon-chartier-grands-blvds', cuisineType: ['french', 'bistro'], lat: 48.8725, lng: 2.3428, avgMealPrice: 9.00, priceCurrency: 'EUR', valueScore: 4.6, tasteScore: 4.2, portionScore: 4.5, totalReviews: 4567, photoUrl: PHOTOS.french, distance: 500, purposeFit: 0.88, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'par-15', name: { original: 'Bouillon Pigalle', en: 'Bouillon Pigalle', romanized: 'Bouillon Pigalle' }, slug: 'bouillon-pigalle', cuisineType: ['french', 'bistro'], lat: 48.8822, lng: 2.3370, avgMealPrice: 9.50, priceCurrency: 'EUR', valueScore: 4.5, tasteScore: 4.3, portionScore: 4.4, totalReviews: 2345, photoUrl: PHOTOS.french, distance: 600, purposeFit: 0.87, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'par-16', name: { original: 'Chez Janou', en: 'Chez Janou', romanized: 'Chez Janou' }, slug: 'chez-janou-marais', cuisineType: ['french', 'bistro'], lat: 48.8565, lng: 2.3645, avgMealPrice: 11.50, priceCurrency: 'EUR', valueScore: 4.1, tasteScore: 4.4, portionScore: 4.0, totalReviews: 1234, photoUrl: PHOTOS.french, distance: 300, purposeFit: 0.80, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Chinese / Market ---
    { id: 'par-17', name: { original: 'Chez Ly', en: 'Chez Ly Chinese', romanized: 'Chez Ly' }, slug: 'chez-ly-17eme', cuisineType: ['chinese', 'cantonese'], lat: 48.8782, lng: 2.3135, avgMealPrice: 8.00, priceCurrency: 'EUR', valueScore: 4.2, tasteScore: 4.0, portionScore: 4.1, totalReviews: 456, photoUrl: PHOTOS.chinese, distance: 550, purposeFit: 0.82, isChain: false, freshnessIndicator: { label: 'Verified 1-3 months ago', color: 'yellow', icon: 'clock' } },
    { id: 'par-18', name: { original: 'Le Cambodge', en: 'Le Cambodge', romanized: 'Le Cambodge' }, slug: 'le-cambodge-canal-st-martin', cuisineType: ['cambodian', 'asian'], lat: 48.8710, lng: 2.3660, avgMealPrice: 8.50, priceCurrency: 'EUR', valueScore: 4.4, tasteScore: 4.3, portionScore: 4.2, totalReviews: 1567, photoUrl: PHOTOS.thai, distance: 380, purposeFit: 0.85, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'par-19', name: { original: 'Chez Alain Miam Miam', en: 'Chez Alain Miam Miam', romanized: 'Chez Alain Miam Miam' }, slug: 'chez-alain-marche-enfants-rouges', cuisineType: ['french', 'market', 'sandwich'], lat: 48.8633, lng: 2.3625, avgMealPrice: 7.00, priceCurrency: 'EUR', valueScore: 4.5, tasteScore: 4.4, portionScore: 4.0, totalReviews: 876, photoUrl: PHOTOS.french, distance: 290, purposeFit: 0.88, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'par-20', name: { original: 'Miznon', en: 'Miznon', romanized: 'Miznon' }, slug: 'miznon-marais', cuisineType: ['israeli', 'pita'], lat: 48.8610, lng: 2.3575, avgMealPrice: 8.00, priceCurrency: 'EUR', valueScore: 4.3, tasteScore: 4.5, portionScore: 3.8, totalReviews: 1234, photoUrl: PHOTOS.kebab, distance: 270, purposeFit: 0.85, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
  ],

  // =====================================================================
  // SINGAPORE
  // =====================================================================
  singapore: [
    // --- Hawker Centers ---
    { id: 'sg-1', name: { original: 'Tian Tian Hainanese Chicken Rice', en: 'Tian Tian Chicken Rice', romanized: 'Tian Tian' }, slug: 'tian-tian-maxwell', cuisineType: ['hawker', 'chicken-rice'], lat: 1.2805, lng: 103.8448, avgMealPrice: 5.00, priceCurrency: 'SGD', valueScore: 4.8, tasteScore: 4.7, portionScore: 4.0, totalReviews: 4567, photoUrl: PHOTOS.hawker, distance: 200, purposeFit: 0.95, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'sg-2', name: { original: 'Boon Tong Kee', en: 'Boon Tong Kee Chicken Rice', romanized: 'Boon Tong Kee' }, slug: 'boon-tong-kee-balestier', cuisineType: ['hawker', 'chicken-rice'], lat: 1.3260, lng: 103.8426, avgMealPrice: 5.50, priceCurrency: 'SGD', valueScore: 4.6, tasteScore: 4.6, portionScore: 4.2, totalReviews: 2345, photoUrl: PHOTOS.hawker, distance: 400, purposeFit: 0.90, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'sg-3', name: { original: 'Hill Street Tai Hwa Pork Noodle', en: 'Hill Street Tai Hwa Pork Noodle', romanized: 'Tai Hwa' }, slug: 'tai-hwa-crawford-lane', cuisineType: ['hawker', 'noodles'], lat: 1.3033, lng: 103.8570, avgMealPrice: 8.00, priceCurrency: 'SGD', valueScore: 4.3, tasteScore: 4.9, portionScore: 3.8, totalReviews: 3456, photoUrl: PHOTOS.hawker, distance: 350, purposeFit: 0.82, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'sg-4', name: { original: 'Lau Pa Sat Satay', en: 'Lau Pa Sat Satay Stall', romanized: 'Lau Pa Sat' }, slug: 'lau-pa-sat-satay', cuisineType: ['hawker', 'satay'], lat: 1.2805, lng: 103.8506, avgMealPrice: 6.00, priceCurrency: 'SGD', valueScore: 4.5, tasteScore: 4.4, portionScore: 4.0, totalReviews: 2345, photoUrl: PHOTOS.hawker, distance: 180, purposeFit: 0.90, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'sg-5', name: { original: 'Tiong Bahru Market Chwee Kueh', en: 'Tiong Bahru Chwee Kueh', romanized: 'Tiong Bahru Chwee Kueh' }, slug: 'tiong-bahru-chwee-kueh', cuisineType: ['hawker', 'local'], lat: 1.2847, lng: 103.8320, avgMealPrice: 3.00, priceCurrency: 'SGD', valueScore: 4.9, tasteScore: 4.3, portionScore: 3.8, totalReviews: 1234, photoUrl: PHOTOS.hawker, distance: 500, purposeFit: 0.95, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Laksa ---
    { id: 'sg-6', name: { original: '328 Katong Laksa', en: '328 Katong Laksa', romanized: '328 Katong Laksa' }, slug: '328-katong-laksa', cuisineType: ['hawker', 'laksa'], lat: 1.3050, lng: 103.9052, avgMealPrice: 6.00, priceCurrency: 'SGD', valueScore: 4.6, tasteScore: 4.7, portionScore: 4.0, totalReviews: 2345, photoUrl: PHOTOS.hawker, distance: 800, purposeFit: 0.88, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'sg-7', name: { original: 'Sungei Road Laksa', en: 'Sungei Road Laksa', romanized: 'Sungei Road Laksa' }, slug: 'sungei-road-laksa', cuisineType: ['hawker', 'laksa'], lat: 1.3053, lng: 103.8575, avgMealPrice: 3.00, priceCurrency: 'SGD', valueScore: 4.9, tasteScore: 4.5, portionScore: 3.5, totalReviews: 1567, photoUrl: PHOTOS.hawker, distance: 360, purposeFit: 0.95, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Roti Prata ---
    { id: 'sg-8', name: { original: 'Mr and Mrs Mohgan', en: 'Mr and Mrs Mohgan Super Crispy Prata', romanized: 'Mohgan Prata' }, slug: 'mohgan-prata-jln-kayu', cuisineType: ['indian', 'prata'], lat: 1.3590, lng: 103.8710, avgMealPrice: 4.00, priceCurrency: 'SGD', valueScore: 4.7, tasteScore: 4.6, portionScore: 4.0, totalReviews: 1234, photoUrl: PHOTOS.indian, distance: 900, purposeFit: 0.92, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'sg-9', name: { original: 'The Roti Prata House', en: 'The Roti Prata House', romanized: 'Roti Prata House' }, slug: 'roti-prata-house-upper-thomson', cuisineType: ['indian', 'prata'], lat: 1.3510, lng: 103.8360, avgMealPrice: 3.50, priceCurrency: 'SGD', valueScore: 4.8, tasteScore: 4.4, portionScore: 4.2, totalReviews: 987, photoUrl: PHOTOS.indian, distance: 850, purposeFit: 0.93, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Nasi Lemak ---
    { id: 'sg-10', name: { original: 'The Coconut Club', en: 'The Coconut Club', romanized: 'The Coconut Club' }, slug: 'coconut-club-ann-siang', cuisineType: ['malay', 'nasi-lemak'], lat: 1.2810, lng: 103.8470, avgMealPrice: 10.00, priceCurrency: 'SGD', valueScore: 4.0, tasteScore: 4.6, portionScore: 3.8, totalReviews: 1567, photoUrl: PHOTOS.hawker, distance: 220, purposeFit: 0.78, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'sg-11', name: { original: 'Ponggol Nasi Lemak', en: 'Ponggol Nasi Lemak', romanized: 'Ponggol Nasi Lemak' }, slug: 'ponggol-nasi-lemak', cuisineType: ['malay', 'nasi-lemak'], lat: 1.3133, lng: 103.8590, avgMealPrice: 4.50, priceCurrency: 'SGD', valueScore: 4.7, tasteScore: 4.5, portionScore: 4.3, totalReviews: 1234, photoUrl: PHOTOS.hawker, distance: 380, purposeFit: 0.92, isChain: false, freshnessIndicator: { label: 'Verified 1-3 months ago', color: 'yellow', icon: 'clock' } },

    // --- Kopitiam Chains ---
    { id: 'sg-12', name: { original: 'Toast Box', en: 'Toast Box', romanized: 'Toast Box' }, slug: 'toast-box-raffles-place', cuisineType: ['kopitiam', 'breakfast'], lat: 1.2835, lng: 103.8510, avgMealPrice: 5.50, priceCurrency: 'SGD', valueScore: 4.2, tasteScore: 3.8, portionScore: 3.5, totalReviews: 678, photoUrl: PHOTOS.coffee, distance: 150, purposeFit: 0.85, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'sg-13', name: { original: 'Ya Kun Kaya Toast', en: 'Ya Kun Kaya Toast', romanized: 'Ya Kun' }, slug: 'ya-kun-tanjong-pagar', cuisineType: ['kopitiam', 'breakfast'], lat: 1.2790, lng: 103.8455, avgMealPrice: 4.80, priceCurrency: 'SGD', valueScore: 4.4, tasteScore: 4.0, portionScore: 3.5, totalReviews: 1234, photoUrl: PHOTOS.coffee, distance: 250, purposeFit: 0.88, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'sg-14', name: { original: 'Killiney Kopitiam', en: 'Killiney Kopitiam', romanized: 'Killiney Kopitiam' }, slug: 'killiney-kopitiam', cuisineType: ['kopitiam', 'breakfast'], lat: 1.2890, lng: 103.8405, avgMealPrice: 5.00, priceCurrency: 'SGD', valueScore: 4.3, tasteScore: 3.9, portionScore: 3.6, totalReviews: 987, photoUrl: PHOTOS.coffee, distance: 300, purposeFit: 0.86, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- More hawker favorites ---
    { id: 'sg-15', name: { original: 'Ah Heng Curry Chicken Bee Hoon', en: 'Ah Heng Curry Chicken Noodle', romanized: 'Ah Heng' }, slug: 'ah-heng-hong-lim', cuisineType: ['hawker', 'curry-noodle'], lat: 1.2840, lng: 103.8465, avgMealPrice: 4.50, priceCurrency: 'SGD', valueScore: 4.6, tasteScore: 4.5, portionScore: 4.0, totalReviews: 876, photoUrl: PHOTOS.hawker, distance: 200, purposeFit: 0.90, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'sg-16', name: { original: 'Outram Park Fried Kway Teow', en: 'Outram Park Fried Kway Teow', romanized: 'Outram Fried Kway Teow' }, slug: 'outram-fried-kway-teow', cuisineType: ['hawker', 'noodles'], lat: 1.2817, lng: 103.8380, avgMealPrice: 5.00, priceCurrency: 'SGD', valueScore: 4.5, tasteScore: 4.6, portionScore: 3.8, totalReviews: 765, photoUrl: PHOTOS.hawker, distance: 350, purposeFit: 0.88, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'sg-17', name: { original: 'Heng Huat Boon Lay', en: 'Heng Huat Roast Duck Noodle', romanized: 'Heng Huat' }, slug: 'heng-huat-maxwell', cuisineType: ['hawker', 'roast-meat'], lat: 1.2802, lng: 103.8450, avgMealPrice: 4.50, priceCurrency: 'SGD', valueScore: 4.5, tasteScore: 4.4, portionScore: 4.1, totalReviews: 654, photoUrl: PHOTOS.hawker, distance: 210, purposeFit: 0.88, isChain: false, freshnessIndicator: { label: 'Verified 1-3 months ago', color: 'yellow', icon: 'clock' } },
    { id: 'sg-18', name: { original: 'Song Fa Bak Kut Teh', en: 'Song Fa Bak Kut Teh', romanized: 'Song Fa' }, slug: 'song-fa-bak-kut-teh', cuisineType: ['chinese', 'bak-kut-teh'], lat: 1.2888, lng: 103.8455, avgMealPrice: 7.50, priceCurrency: 'SGD', valueScore: 4.4, tasteScore: 4.6, portionScore: 4.0, totalReviews: 2345, photoUrl: PHOTOS.chinese, distance: 280, purposeFit: 0.85, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'sg-19', name: { original: 'A Noodle Story', en: 'A Noodle Story', romanized: 'A Noodle Story' }, slug: 'a-noodle-story-amoy', cuisineType: ['hawker', 'noodles'], lat: 1.2800, lng: 103.8472, avgMealPrice: 6.00, priceCurrency: 'SGD', valueScore: 4.5, tasteScore: 4.7, portionScore: 3.8, totalReviews: 1567, photoUrl: PHOTOS.ramen, distance: 190, purposeFit: 0.88, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'sg-20', name: { original: 'Maxwell Fuzhou Oyster Cake', en: 'Maxwell Fuzhou Oyster Cake', romanized: 'Fuzhou Oyster Cake' }, slug: 'maxwell-fuzhou-oyster-cake', cuisineType: ['hawker', 'local'], lat: 1.2803, lng: 103.8446, avgMealPrice: 3.50, priceCurrency: 'SGD', valueScore: 4.8, tasteScore: 4.2, portionScore: 3.8, totalReviews: 543, photoUrl: PHOTOS.hawker, distance: 205, purposeFit: 0.93, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
  ],

  // =====================================================================
  // DUBAI
  // =====================================================================
  dubai: [
    // --- Shawarma ---
    { id: 'dxb-1', name: { original: 'Al Mallah', en: 'Al Mallah Cafeteria', romanized: 'Al Mallah' }, slug: 'al-mallah-al-dhiyafah', cuisineType: ['lebanese', 'shawarma'], lat: 25.2333, lng: 55.2710, avgMealPrice: 15, priceCurrency: 'AED', valueScore: 4.7, tasteScore: 4.5, portionScore: 4.3, totalReviews: 2345, photoUrl: PHOTOS.kebab, distance: 200, purposeFit: 0.93, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'dxb-2', name: { original: 'Shawarma King', en: 'Shawarma King', romanized: 'Shawarma King' }, slug: 'shawarma-king-karama', cuisineType: ['arabic', 'shawarma'], lat: 25.2420, lng: 55.3060, avgMealPrice: 12, priceCurrency: 'AED', valueScore: 4.6, tasteScore: 4.3, portionScore: 4.5, totalReviews: 1234, photoUrl: PHOTOS.kebab, distance: 350, purposeFit: 0.92, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'dxb-3', name: { original: 'Laffah', en: 'Laffah Restaurant', romanized: 'Laffah' }, slug: 'laffah-jbr', cuisineType: ['lebanese', 'shawarma'], lat: 25.2080, lng: 55.2730, avgMealPrice: 18, priceCurrency: 'AED', valueScore: 4.3, tasteScore: 4.4, portionScore: 4.2, totalReviews: 876, photoUrl: PHOTOS.kebab, distance: 500, purposeFit: 0.85, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Indian ---
    { id: 'dxb-4', name: { original: 'Ravi Restaurant', en: 'Ravi Restaurant', romanized: 'Ravi Restaurant' }, slug: 'ravi-satwa', cuisineType: ['pakistani', 'indian'], lat: 25.2298, lng: 55.2702, avgMealPrice: 15, priceCurrency: 'AED', valueScore: 4.8, tasteScore: 4.5, portionScore: 4.7, totalReviews: 5678, photoUrl: PHOTOS.indian, distance: 250, purposeFit: 0.95, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'dxb-5', name: { original: 'Delhi Darbar', en: 'Delhi Darbar', romanized: 'Delhi Darbar' }, slug: 'delhi-darbar-karama', cuisineType: ['indian', 'curry'], lat: 25.2435, lng: 55.3055, avgMealPrice: 18, priceCurrency: 'AED', valueScore: 4.5, tasteScore: 4.4, portionScore: 4.5, totalReviews: 2345, photoUrl: PHOTOS.indian, distance: 380, purposeFit: 0.90, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'dxb-6', name: { original: 'Calicut Paragon', en: 'Calicut Paragon', romanized: 'Calicut Paragon' }, slug: 'calicut-paragon-karama', cuisineType: ['indian', 'kerala'], lat: 25.2440, lng: 55.3050, avgMealPrice: 20, priceCurrency: 'AED', valueScore: 4.4, tasteScore: 4.5, portionScore: 4.3, totalReviews: 1567, photoUrl: PHOTOS.indian, distance: 390, purposeFit: 0.85, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Pakistani / Afghan ---
    { id: 'dxb-7', name: { original: 'Karachi Darbar', en: 'Karachi Darbar', romanized: 'Karachi Darbar' }, slug: 'karachi-darbar-deira', cuisineType: ['pakistani', 'biryani'], lat: 25.2680, lng: 55.3180, avgMealPrice: 14, priceCurrency: 'AED', valueScore: 4.7, tasteScore: 4.3, portionScore: 4.8, totalReviews: 3456, photoUrl: PHOTOS.indian, distance: 600, purposeFit: 0.92, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'dxb-8', name: { original: 'Afghan Khorasan Kabab', en: 'Afghan Khorasan Kabab', romanized: 'Afghan Khorasan' }, slug: 'afghan-khorasan-deira', cuisineType: ['afghan', 'kebab'], lat: 25.2660, lng: 55.3170, avgMealPrice: 20, priceCurrency: 'AED', valueScore: 4.4, tasteScore: 4.5, portionScore: 4.5, totalReviews: 1234, photoUrl: PHOTOS.kebab, distance: 580, purposeFit: 0.85, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'dxb-9', name: { original: 'Pak Liyari', en: 'Pak Liyari Restaurant', romanized: 'Pak Liyari' }, slug: 'pak-liyari-al-fahidi', cuisineType: ['pakistani', 'biryani'], lat: 25.2560, lng: 55.2980, avgMealPrice: 12, priceCurrency: 'AED', valueScore: 4.7, tasteScore: 4.2, portionScore: 4.7, totalReviews: 876, photoUrl: PHOTOS.indian, distance: 450, purposeFit: 0.92, isChain: false, freshnessIndicator: { label: 'Verified 1-3 months ago', color: 'yellow', icon: 'clock' } },

    // --- Cafeterias (Local Budget) ---
    { id: 'dxb-10', name: { original: 'Al Ustad Special Kabab', en: 'Al Ustad Special Kabab', romanized: 'Al Ustad' }, slug: 'al-ustad-bur-dubai', cuisineType: ['iranian', 'kebab'], lat: 25.2550, lng: 55.2975, avgMealPrice: 25, priceCurrency: 'AED', valueScore: 4.2, tasteScore: 4.6, portionScore: 4.3, totalReviews: 1567, photoUrl: PHOTOS.kebab, distance: 440, purposeFit: 0.80, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'dxb-11', name: { original: 'Firas Sweets', en: 'Firas Sweets', romanized: 'Firas Sweets' }, slug: 'firas-sweets-sheikh-zayed', cuisineType: ['lebanese', 'sweets'], lat: 25.2300, lng: 55.2720, avgMealPrice: 10, priceCurrency: 'AED', valueScore: 4.5, tasteScore: 4.3, portionScore: 3.8, totalReviews: 678, photoUrl: PHOTOS.kebab, distance: 280, purposeFit: 0.85, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'dxb-12', name: { original: 'Ashwaq Cafeteria', en: 'Ashwaq Cafeteria', romanized: 'Ashwaq' }, slug: 'ashwaq-cafeteria-deira', cuisineType: ['emirati', 'cafeteria'], lat: 25.2700, lng: 55.3200, avgMealPrice: 10, priceCurrency: 'AED', valueScore: 4.8, tasteScore: 3.8, portionScore: 4.5, totalReviews: 456, photoUrl: PHOTOS.kebab, distance: 620, purposeFit: 0.95, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Lebanese ---
    { id: 'dxb-13', name: { original: 'Operation Falafel', en: 'Operation Falafel', romanized: 'Operation Falafel' }, slug: 'operation-falafel-jlt', cuisineType: ['lebanese', 'falafel'], lat: 25.1820, lng: 55.2750, avgMealPrice: 20, priceCurrency: 'AED', valueScore: 4.3, tasteScore: 4.2, portionScore: 4.0, totalReviews: 987, photoUrl: PHOTOS.kebab, distance: 700, purposeFit: 0.85, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'dxb-14', name: { original: 'Zaroob', en: 'Zaroob', romanized: 'Zaroob' }, slug: 'zaroob-sheikh-zayed', cuisineType: ['lebanese', 'street-food'], lat: 25.2285, lng: 55.2690, avgMealPrice: 25, priceCurrency: 'AED', valueScore: 4.2, tasteScore: 4.4, portionScore: 4.2, totalReviews: 1234, photoUrl: PHOTOS.kebab, distance: 310, purposeFit: 0.82, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Filipino ---
    { id: 'dxb-15', name: { original: 'Jollibee', en: 'Jollibee', romanized: 'Jollibee' }, slug: 'jollibee-karama', cuisineType: ['filipino', 'fast-food'], lat: 25.2430, lng: 55.3065, avgMealPrice: 18, priceCurrency: 'AED', valueScore: 4.3, tasteScore: 3.9, portionScore: 4.2, totalReviews: 876, photoUrl: PHOTOS.burger, distance: 370, purposeFit: 0.85, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'dxb-16', name: { original: 'Pinoy Pamilya', en: 'Pinoy Pamilya Restaurant', romanized: 'Pinoy Pamilya' }, slug: 'pinoy-pamilya-al-rigga', cuisineType: ['filipino', 'budget'], lat: 25.2650, lng: 55.3265, avgMealPrice: 15, priceCurrency: 'AED', valueScore: 4.6, tasteScore: 4.0, portionScore: 4.5, totalReviews: 543, photoUrl: PHOTOS.hawker, distance: 550, purposeFit: 0.90, isChain: false, freshnessIndicator: { label: 'Verified 1-3 months ago', color: 'yellow', icon: 'clock' } },

    // --- More Budget ---
    { id: 'dxb-17', name: { original: 'Al Reef Bakery', en: 'Al Reef Lebanese Bakery', romanized: 'Al Reef' }, slug: 'al-reef-bakery', cuisineType: ['lebanese', 'bakery'], lat: 25.2350, lng: 55.2730, avgMealPrice: 10, priceCurrency: 'AED', valueScore: 4.7, tasteScore: 4.1, portionScore: 4.0, totalReviews: 1234, photoUrl: PHOTOS.kebab, distance: 300, purposeFit: 0.92, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'dxb-18', name: { original: 'Bur Dubai Fish Market Cafe', en: 'Fish Market Cafeteria', romanized: 'Fish Market Cafe' }, slug: 'fish-market-cafe-bur-dubai', cuisineType: ['seafood', 'cafeteria'], lat: 25.2570, lng: 55.2960, avgMealPrice: 20, priceCurrency: 'AED', valueScore: 4.3, tasteScore: 4.3, portionScore: 4.2, totalReviews: 567, photoUrl: PHOTOS.british, distance: 460, purposeFit: 0.82, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'dxb-19', name: { original: 'Jaffer Bhai', en: "Jaffer Bhai's", romanized: "Jaffer Bhai's" }, slug: 'jaffer-bhai-karama', cuisineType: ['indian', 'biryani'], lat: 25.2445, lng: 55.3040, avgMealPrice: 16, priceCurrency: 'AED', valueScore: 4.5, tasteScore: 4.4, portionScore: 4.6, totalReviews: 1567, photoUrl: PHOTOS.indian, distance: 400, purposeFit: 0.88, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'dxb-20', name: { original: 'Bu Qtair', en: 'Bu Qtair Seafood', romanized: 'Bu Qtair' }, slug: 'bu-qtair-jumeirah', cuisineType: ['seafood', 'local'], lat: 25.2100, lng: 55.2750, avgMealPrice: 35, priceCurrency: 'AED', valueScore: 4.1, tasteScore: 4.7, portionScore: 4.5, totalReviews: 2345, photoUrl: PHOTOS.british, distance: 480, purposeFit: 0.78, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
  ],

  // =====================================================================
  // SYDNEY
  // =====================================================================
  sydney: [
    // --- Thai ---
    { id: 'syd-1', name: { original: 'Chat Thai', en: 'Chat Thai', romanized: 'Chat Thai' }, slug: 'chat-thai-haymarket', cuisineType: ['thai', 'street-food'], lat: -33.8793, lng: 151.2039, avgMealPrice: 14.00, priceCurrency: 'AUD', valueScore: 4.5, tasteScore: 4.5, portionScore: 4.2, totalReviews: 2345, photoUrl: PHOTOS.thai, distance: 200, purposeFit: 0.88, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'syd-2', name: { original: 'Home Thai', en: 'Home Thai', romanized: 'Home Thai' }, slug: 'home-thai-surry-hills', cuisineType: ['thai', 'noodles'], lat: -33.8810, lng: 151.2110, avgMealPrice: 13.00, priceCurrency: 'AUD', valueScore: 4.4, tasteScore: 4.3, portionScore: 4.0, totalReviews: 876, photoUrl: PHOTOS.thai, distance: 350, purposeFit: 0.85, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Vietnamese ---
    { id: 'syd-3', name: { original: 'Pho An', en: 'Pho An Vietnamese', romanized: 'Pho An' }, slug: 'pho-an-haymarket', cuisineType: ['vietnamese', 'pho'], lat: -33.8795, lng: 151.2045, avgMealPrice: 12.00, priceCurrency: 'AUD', valueScore: 4.6, tasteScore: 4.4, portionScore: 4.3, totalReviews: 1234, photoUrl: PHOTOS.vietnamese, distance: 210, purposeFit: 0.90, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'syd-4', name: { original: 'Marrickville Pork Roll', en: 'Marrickville Pork Roll', romanized: 'Marrickville Pork Roll' }, slug: 'marrickville-pork-roll', cuisineType: ['vietnamese', 'banh-mi'], lat: -33.9115, lng: 151.1550, avgMealPrice: 8.50, priceCurrency: 'AUD', valueScore: 4.8, tasteScore: 4.5, portionScore: 4.5, totalReviews: 1567, photoUrl: PHOTOS.vietnamese, distance: 800, purposeFit: 0.93, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Chinese BBQ ---
    { id: 'syd-5', name: { original: 'BBQ King', en: 'BBQ King', romanized: 'BBQ King' }, slug: 'bbq-king-chinatown', cuisineType: ['chinese', 'bbq'], lat: -33.8775, lng: 151.2050, avgMealPrice: 15.00, priceCurrency: 'AUD', valueScore: 4.3, tasteScore: 4.4, portionScore: 4.5, totalReviews: 1567, photoUrl: PHOTOS.chinese, distance: 180, purposeFit: 0.82, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'syd-6', name: { original: 'Chinese Noodle House', en: 'Chinese Noodle House', romanized: 'Chinese Noodle House' }, slug: 'chinese-noodle-house-haymarket', cuisineType: ['chinese', 'noodles'], lat: -33.8790, lng: 151.2042, avgMealPrice: 12.00, priceCurrency: 'AUD', valueScore: 4.5, tasteScore: 4.2, portionScore: 4.3, totalReviews: 876, photoUrl: PHOTOS.chinese, distance: 205, purposeFit: 0.88, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Fish & Chips ---
    { id: 'syd-7', name: { original: 'Sydney Fish Market Takeaway', en: 'Sydney Fish Market Takeaway', romanized: 'Fish Market Takeaway' }, slug: 'fish-market-takeaway-pyrmont', cuisineType: ['seafood', 'fish-and-chips'], lat: -33.8700, lng: 151.1925, avgMealPrice: 15.00, priceCurrency: 'AUD', valueScore: 4.2, tasteScore: 4.5, portionScore: 4.2, totalReviews: 2345, photoUrl: PHOTOS.british, distance: 500, purposeFit: 0.82, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'syd-8', name: { original: "Fisherman's Wharf", en: "Fisherman's Wharf Fish & Chips", romanized: "Fisherman's Wharf" }, slug: 'fishermans-wharf-manly', cuisineType: ['seafood', 'fish-and-chips'], lat: -33.8000, lng: 151.2870, avgMealPrice: 14.00, priceCurrency: 'AUD', valueScore: 4.3, tasteScore: 4.3, portionScore: 4.4, totalReviews: 987, photoUrl: PHOTOS.british, distance: 1200, purposeFit: 0.83, isChain: false, freshnessIndicator: { label: 'Verified 1-3 months ago', color: 'yellow', icon: 'clock' } },

    // --- Kebab ---
    { id: 'syd-9', name: { original: 'Kebab Station', en: 'Kebab Station', romanized: 'Kebab Station' }, slug: 'kebab-station-newtown', cuisineType: ['turkish', 'kebab'], lat: -33.8973, lng: 151.1795, avgMealPrice: 11.00, priceCurrency: 'AUD', valueScore: 4.5, tasteScore: 4.2, portionScore: 4.5, totalReviews: 654, photoUrl: PHOTOS.kebab, distance: 600, purposeFit: 0.88, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'syd-10', name: { original: 'Ali Baba', en: 'Ali Baba Lebanese', romanized: 'Ali Baba' }, slug: 'ali-baba-town-hall', cuisineType: ['lebanese', 'kebab'], lat: -33.8735, lng: 151.2070, avgMealPrice: 10.50, priceCurrency: 'AUD', valueScore: 4.4, tasteScore: 4.0, portionScore: 4.3, totalReviews: 876, photoUrl: PHOTOS.kebab, distance: 250, purposeFit: 0.87, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Pie Shops ---
    { id: 'syd-11', name: { original: "Harry's Cafe de Wheels", en: "Harry's Cafe de Wheels", romanized: "Harry's Cafe de Wheels" }, slug: 'harrys-cafe-woolloomooloo', cuisineType: ['australian', 'pie'], lat: -33.8700, lng: 151.2220, avgMealPrice: 9.50, priceCurrency: 'AUD', valueScore: 4.3, tasteScore: 4.1, portionScore: 4.0, totalReviews: 1567, photoUrl: PHOTOS.british, distance: 400, purposeFit: 0.85, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'syd-12', name: { original: 'Pie Face', en: 'Pie Face', romanized: 'Pie Face' }, slug: 'pie-face-george-st', cuisineType: ['australian', 'pie'], lat: -33.8710, lng: 151.2065, avgMealPrice: 8.00, priceCurrency: 'AUD', valueScore: 4.2, tasteScore: 3.7, portionScore: 3.8, totalReviews: 543, photoUrl: PHOTOS.british, distance: 220, purposeFit: 0.88, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Nando's ---
    { id: 'syd-13', name: { original: "Nando's", en: "Nando's George St", romanized: "Nando's" }, slug: 'nandos-george-st', cuisineType: ['chicken', 'portuguese'], lat: -33.8720, lng: 151.2060, avgMealPrice: 15.00, priceCurrency: 'AUD', valueScore: 4.0, tasteScore: 4.1, portionScore: 3.9, totalReviews: 678, photoUrl: PHOTOS.burger, distance: 230, purposeFit: 0.82, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- More budget spots ---
    { id: 'syd-14', name: { original: 'Mamak', en: 'Mamak Malaysian', romanized: 'Mamak' }, slug: 'mamak-haymarket', cuisineType: ['malaysian', 'roti'], lat: -33.8785, lng: 151.2055, avgMealPrice: 12.00, priceCurrency: 'AUD', valueScore: 4.5, tasteScore: 4.5, portionScore: 4.2, totalReviews: 2345, photoUrl: PHOTOS.hawker, distance: 195, purposeFit: 0.88, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'syd-15', name: { original: "Guzman y Gomez", en: "Guzman y Gomez", romanized: "Guzman y Gomez" }, slug: 'guzman-y-gomez-town-hall', cuisineType: ['mexican', 'fast-casual'], lat: -33.8730, lng: 151.2070, avgMealPrice: 14.00, priceCurrency: 'AUD', valueScore: 4.1, tasteScore: 4.0, portionScore: 4.0, totalReviews: 567, photoUrl: PHOTOS.mexican, distance: 240, purposeFit: 0.82, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'syd-16', name: { original: 'Soul Burger', en: 'Soul Burger', romanized: 'Soul Burger' }, slug: 'soul-burger-randwick', cuisineType: ['burger', 'vegan'], lat: -33.8610, lng: 151.2090, avgMealPrice: 16.00, priceCurrency: 'AUD', valueScore: 3.9, tasteScore: 4.2, portionScore: 3.8, totalReviews: 432, photoUrl: PHOTOS.burger, distance: 350, purposeFit: 0.78, isChain: true, freshnessIndicator: { label: 'Verified 1-3 months ago', color: 'yellow', icon: 'clock' } },
    { id: 'syd-17', name: { original: 'Mappen', en: 'Mappen Udon', romanized: 'Mappen' }, slug: 'mappen-world-square', cuisineType: ['japanese', 'udon'], lat: -33.8770, lng: 151.2065, avgMealPrice: 13.00, priceCurrency: 'AUD', valueScore: 4.4, tasteScore: 4.3, portionScore: 4.0, totalReviews: 876, photoUrl: PHOTOS.ramen, distance: 190, purposeFit: 0.85, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'syd-18', name: { original: 'Ippudo', en: 'Ippudo Ramen', romanized: 'Ippudo' }, slug: 'ippudo-westfield', cuisineType: ['japanese', 'ramen'], lat: -33.8715, lng: 151.2080, avgMealPrice: 18.00, priceCurrency: 'AUD', valueScore: 4.0, tasteScore: 4.5, portionScore: 3.8, totalReviews: 1234, photoUrl: PHOTOS.ramen, distance: 260, purposeFit: 0.78, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'syd-19', name: { original: 'Messina Gelato', en: 'Gelato Messina', romanized: 'Gelato Messina' }, slug: 'gelato-messina-darlinghurst', cuisineType: ['dessert', 'gelato'], lat: -33.8780, lng: 151.2190, avgMealPrice: 8.50, priceCurrency: 'AUD', valueScore: 4.3, tasteScore: 4.8, portionScore: 3.5, totalReviews: 2345, photoUrl: PHOTOS.coffee, distance: 380, purposeFit: 0.70, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'syd-20', name: { original: 'Lankan Filling Station', en: 'Lankan Filling Station', romanized: 'Lankan Filling Station' }, slug: 'lankan-filling-darlinghurst', cuisineType: ['sri-lankan', 'curry'], lat: -33.8765, lng: 151.2185, avgMealPrice: 15.00, priceCurrency: 'AUD', valueScore: 4.4, tasteScore: 4.5, portionScore: 4.2, totalReviews: 987, photoUrl: PHOTOS.indian, distance: 370, purposeFit: 0.85, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
  ],

  // =====================================================================
  // TAIPEI
  // =====================================================================
  taipei: [
    // --- Night Market Food ---
    { id: 'tpe-1', name: { original: '士林夜市 大餅包小餅', en: 'Shilin Night Market Big Cake Wraps Small Cake', romanized: 'Shilin Da Bing Bao Xiao Bing' }, slug: 'shilin-da-bing-bao-xiao-bing', cuisineType: ['taiwanese', 'night-market'], lat: 25.0880, lng: 121.5245, avgMealPrice: 60, priceCurrency: 'TWD', valueScore: 4.7, tasteScore: 4.3, portionScore: 3.8, totalReviews: 1234, photoUrl: PHOTOS.hawker, distance: 200, purposeFit: 0.92, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'tpe-2', name: { original: '士林夜市 豪大大雞排', en: 'Hot Star Large Fried Chicken', romanized: 'Hao Da Da Ji Pai' }, slug: 'hot-star-chicken-shilin', cuisineType: ['taiwanese', 'fried-chicken'], lat: 25.0882, lng: 121.5248, avgMealPrice: 70, priceCurrency: 'TWD', valueScore: 4.6, tasteScore: 4.4, portionScore: 4.5, totalReviews: 2345, photoUrl: PHOTOS.hawker, distance: 210, purposeFit: 0.90, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'tpe-3', name: { original: '饒河夜市 胡椒餅', en: 'Raohe Pepper Bun', romanized: 'Raohe Hu Jiao Bing' }, slug: 'raohe-pepper-bun', cuisineType: ['taiwanese', 'night-market'], lat: 25.0510, lng: 121.5770, avgMealPrice: 60, priceCurrency: 'TWD', valueScore: 4.8, tasteScore: 4.7, portionScore: 3.5, totalReviews: 3456, photoUrl: PHOTOS.hawker, distance: 300, purposeFit: 0.93, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'tpe-4', name: { original: '寧夏夜市 劉芋仔', en: 'Ningxia Taro Balls', romanized: 'Liu Yu Zai' }, slug: 'liu-yu-zai-ningxia', cuisineType: ['taiwanese', 'night-market'], lat: 25.0555, lng: 121.5155, avgMealPrice: 50, priceCurrency: 'TWD', valueScore: 4.7, tasteScore: 4.5, portionScore: 3.5, totalReviews: 1567, photoUrl: PHOTOS.hawker, distance: 250, purposeFit: 0.92, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Beef Noodle Soup ---
    { id: 'tpe-5', name: { original: '永康牛肉麵', en: 'Yongkang Beef Noodle', romanized: 'Yongkang Niu Rou Mian' }, slug: 'yongkang-beef-noodle', cuisineType: ['taiwanese', 'beef-noodle'], lat: 25.0330, lng: 121.5295, avgMealPrice: 200, priceCurrency: 'TWD', valueScore: 4.3, tasteScore: 4.7, portionScore: 4.2, totalReviews: 4567, photoUrl: PHOTOS.ramen, distance: 400, purposeFit: 0.82, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'tpe-6', name: { original: '林東芳牛肉麵', en: 'Lin Dong Fang Beef Noodle', romanized: 'Lin Dong Fang' }, slug: 'lin-dong-fang-beef-noodle', cuisineType: ['taiwanese', 'beef-noodle'], lat: 25.0465, lng: 121.5435, avgMealPrice: 180, priceCurrency: 'TWD', valueScore: 4.4, tasteScore: 4.8, portionScore: 4.3, totalReviews: 2345, photoUrl: PHOTOS.ramen, distance: 350, purposeFit: 0.85, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'tpe-7', name: { original: '老張牛肉麵', en: 'Old Zhang Beef Noodle', romanized: 'Lao Zhang Niu Rou Mian' }, slug: 'lao-zhang-beef-noodle', cuisineType: ['taiwanese', 'beef-noodle'], lat: 25.0410, lng: 121.5080, avgMealPrice: 150, priceCurrency: 'TWD', valueScore: 4.6, tasteScore: 4.5, portionScore: 4.4, totalReviews: 987, photoUrl: PHOTOS.ramen, distance: 320, purposeFit: 0.88, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Bento Box Shops ---
    { id: 'tpe-8', name: { original: '池上木片便當', en: 'Chishang Wooden Bento', romanized: 'Chishang Mu Pian Bian Dang' }, slug: 'chishang-bento-taipei-station', cuisineType: ['taiwanese', 'bento'], lat: 25.0478, lng: 121.5170, avgMealPrice: 80, priceCurrency: 'TWD', valueScore: 4.7, tasteScore: 4.1, portionScore: 4.3, totalReviews: 1234, photoUrl: PHOTOS.hawker, distance: 280, purposeFit: 0.92, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'tpe-9', name: { original: '台鐵便當', en: 'Taiwan Railway Bento', romanized: 'Tai Tie Bian Dang' }, slug: 'taiwan-railway-bento', cuisineType: ['taiwanese', 'bento'], lat: 25.0480, lng: 121.5175, avgMealPrice: 60, priceCurrency: 'TWD', valueScore: 4.8, tasteScore: 3.9, portionScore: 4.2, totalReviews: 2345, photoUrl: PHOTOS.hawker, distance: 285, purposeFit: 0.95, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Bubble Tea + Light Meals ---
    { id: 'tpe-10', name: { original: '春水堂', en: 'Chun Shui Tang', romanized: 'Chun Shui Tang' }, slug: 'chun-shui-tang-zhongxiao', cuisineType: ['taiwanese', 'bubble-tea', 'light-meal'], lat: 25.0415, lng: 121.5450, avgMealPrice: 150, priceCurrency: 'TWD', valueScore: 4.2, tasteScore: 4.4, portionScore: 3.5, totalReviews: 1567, photoUrl: PHOTOS.coffee, distance: 360, purposeFit: 0.78, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'tpe-11', name: { original: '50嵐', en: '50 Lan Bubble Tea', romanized: 'Wu Shi Lan' }, slug: '50-lan-da-an', cuisineType: ['taiwanese', 'bubble-tea'], lat: 25.0335, lng: 121.5430, avgMealPrice: 50, priceCurrency: 'TWD', valueScore: 4.6, tasteScore: 4.3, portionScore: 3.5, totalReviews: 876, photoUrl: PHOTOS.coffee, distance: 380, purposeFit: 0.88, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Taiwanese Breakfast ---
    { id: 'tpe-12', name: { original: '阜杭豆漿', en: 'Fu Hang Soy Milk', romanized: 'Fu Hang Dou Jiang' }, slug: 'fu-hang-soy-milk', cuisineType: ['taiwanese', 'breakfast'], lat: 25.0449, lng: 121.5280, avgMealPrice: 60, priceCurrency: 'TWD', valueScore: 4.8, tasteScore: 4.6, portionScore: 4.0, totalReviews: 5678, photoUrl: PHOTOS.hawker, distance: 290, purposeFit: 0.93, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'tpe-13', name: { original: '永和豆漿大王', en: 'Yonghe Soy Milk King', romanized: 'Yonghe Dou Jiang Da Wang' }, slug: 'yonghe-soy-milk-king', cuisineType: ['taiwanese', 'breakfast'], lat: 25.0390, lng: 121.5210, avgMealPrice: 55, priceCurrency: 'TWD', valueScore: 4.7, tasteScore: 4.2, portionScore: 4.0, totalReviews: 1234, photoUrl: PHOTOS.hawker, distance: 310, purposeFit: 0.92, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'tpe-14', name: { original: '美而美早餐', en: 'Mei Er Mei Breakfast', romanized: 'Mei Er Mei' }, slug: 'mei-er-mei-breakfast', cuisineType: ['taiwanese', 'breakfast'], lat: 25.0440, lng: 121.5330, avgMealPrice: 50, priceCurrency: 'TWD', valueScore: 4.6, tasteScore: 3.8, portionScore: 3.8, totalReviews: 654, photoUrl: PHOTOS.hawker, distance: 260, purposeFit: 0.92, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },

    // --- Lu Rou Fan ---
    { id: 'tpe-15', name: { original: '金峰魯肉飯', en: 'Jin Feng Braised Pork Rice', romanized: 'Jin Feng Lu Rou Fan' }, slug: 'jin-feng-lu-rou-fan', cuisineType: ['taiwanese', 'lu-rou-fan'], lat: 25.0328, lng: 121.5115, avgMealPrice: 50, priceCurrency: 'TWD', valueScore: 4.9, tasteScore: 4.7, portionScore: 4.0, totalReviews: 4567, photoUrl: PHOTOS.hawker, distance: 370, purposeFit: 0.95, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'tpe-16', name: { original: '鬍鬚張魯肉飯', en: 'Formosa Chang Braised Pork Rice', romanized: 'Hu Xu Zhang Lu Rou Fan' }, slug: 'formosa-chang-lu-rou-fan', cuisineType: ['taiwanese', 'lu-rou-fan'], lat: 25.0485, lng: 121.5180, avgMealPrice: 55, priceCurrency: 'TWD', valueScore: 4.5, tasteScore: 4.2, portionScore: 4.0, totalReviews: 2345, photoUrl: PHOTOS.hawker, distance: 270, purposeFit: 0.90, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'tpe-17', name: { original: '天天利美食坊', en: 'Tian Tian Li Snack Shop', romanized: 'Tian Tian Li' }, slug: 'tian-tian-li-ximending', cuisineType: ['taiwanese', 'lu-rou-fan'], lat: 25.0438, lng: 121.5070, avgMealPrice: 60, priceCurrency: 'TWD', valueScore: 4.6, tasteScore: 4.4, portionScore: 4.2, totalReviews: 1234, photoUrl: PHOTOS.hawker, distance: 290, purposeFit: 0.90, isChain: false, freshnessIndicator: { label: 'Verified 1-3 months ago', color: 'yellow', icon: 'clock' } },

    // --- More Taipei budget spots ---
    { id: 'tpe-18', name: { original: '鼎泰豐', en: 'Din Tai Fung', romanized: 'Din Tai Fung' }, slug: 'din-tai-fung-xinyi', cuisineType: ['taiwanese', 'xiaolongbao'], lat: 25.0333, lng: 121.5297, avgMealPrice: 200, priceCurrency: 'TWD', valueScore: 4.2, tasteScore: 4.9, portionScore: 3.8, totalReviews: 6789, photoUrl: PHOTOS.chinese, distance: 395, purposeFit: 0.78, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'tpe-19', name: { original: '度小月擔仔麵', en: 'Du Xiao Yue Danzai Noodle', romanized: 'Du Xiao Yue' }, slug: 'du-xiao-yue-yongkang', cuisineType: ['taiwanese', 'danzai-noodle'], lat: 25.0326, lng: 121.5290, avgMealPrice: 80, priceCurrency: 'TWD', valueScore: 4.5, tasteScore: 4.4, portionScore: 3.5, totalReviews: 1567, photoUrl: PHOTOS.ramen, distance: 405, purposeFit: 0.88, isChain: true, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'tpe-20', name: { original: '師大夜市 燈籠滷味', en: 'Shida Night Market Stewed Snacks', romanized: 'Shida Deng Long Lu Wei' }, slug: 'shida-lu-wei', cuisineType: ['taiwanese', 'night-market', 'lu-wei'], lat: 25.0267, lng: 121.5280, avgMealPrice: 70, priceCurrency: 'TWD', valueScore: 4.6, tasteScore: 4.3, portionScore: 4.0, totalReviews: 876, photoUrl: PHOTOS.hawker, distance: 420, purposeFit: 0.90, isChain: false, freshnessIndicator: { label: 'Recently Verified', color: 'green', icon: 'check' } },
    { id: 'tpe-21', name: { original: '三商巧福', en: 'San Shang Qiao Fu Beef Noodle', romanized: 'San Shang Qiao Fu' }, slug: 'san-shang-qiao-fu', cuisineType: ['taiwanese', 'beef-noodle'], lat: 25.0460, lng: 121.5165, avgMealPrice: 100, priceCurrency: 'TWD', valueScore: 4.4, tasteScore: 3.9, portionScore: 4.0, totalReviews: 567, photoUrl: PHOTOS.ramen, distance: 275, purposeFit: 0.88, isChain: true, freshnessIndicator: { label: 'Verified 1-3 months ago', color: 'yellow', icon: 'clock' } },
  ],
};
